# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: HRL documentation
author: Guillermo Aguilar, Joris Vincent, Torsten Betz, Sacha Sokoloski
#logo: logo.png
copyright: "2024. Licence: GPLv2"  # Copyright year to be placed in the footer

execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: hrl-documentation.tex

# HTML-specific settings
html:
  home_page_in_navbar         : true
  use_repository_button       : true  # Whether to add a link to your repository button
  show_navbar_depth: 1


# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/computational-psychology/hrl/  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

   
    
sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinx.ext.intersphinx
    
  config:
    intersphinx_mapping:
        python:
          - 'https://docs.python.org/3/'
          - null
        numpy [stable]:
          - 'https://numpy.org/doc/stable/'
          - null
        matplotlib [stable]:
          - 'https://matplotlib.org/stable/'
          - null
        scipy [latest]:
          - 'https://docs.scipy.org/doc/scipy/'
          - null
        pillow [latest]:
          - 'https://pillow.readthedocs.io/en/latest/'
          - null
    suppress_warnings: ["etoc.toctree"]

